package com.salam.androidwebserver;

import android.Manifest;
import android.animation.ValueAnimator;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.*;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.zip.*;

public class MainActivity extends Activity {
    static final int BG=Color.rgb(2,11,23), CARD=Color.rgb(7,27,51), CARD2=Color.rgb(8,39,72);
    static final int BLUE=Color.rgb(10,139,255), CYAN=Color.rgb(28,211,255), GREEN=Color.rgb(18,232,166);
    static final int RED=Color.rgb(255,70,82), PURPLE=Color.rgb(176,86,255), YELLOW=Color.rgb(255,205,40);
    static final int ORANGE=Color.rgb(255,140,35), WHITE=Color.rgb(247,250,255), MUTED=Color.rgb(155,183,213);
    static final int[] LED={GREEN,CYAN,PURPLE,YELLOW,WHITE,ORANGE,RED};
    static final int HOME=1,FILES=2,LOGS=3,SETTINGS=4,NETWORK=5,ABOUT=6,BROWSER=7;

    SharedPreferences pref; Handler h=new Handler(Looper.getMainLooper());
    FrameLayout root; LinearLayout body; TextView title; int screen=HOME; String folder="/"; File pending;
    int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
    TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
    GradientDrawable gd(int a,int b,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setTextColor(WHITE);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(gd(BLUE,CYAN,24));return b;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(11),dp(13),dp(11));c.setBackground(gd(CARD,CARD2,21));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(3),dp(5),dp(3),dp(5));c.setLayoutParams(p);return c;}
    TextView section(String s){TextView v=tv(s,11,CYAN);v.setTypeface(null,1);v.setPadding(dp(9),dp(10),0,dp(4));return v;}
    EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(WHITE);e.setHintTextColor(MUTED);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackground(gd(Color.rgb(3,19,37),Color.rgb(5,31,55),15));return e;}

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);pref=getSharedPreferences("server",MODE_PRIVATE);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},77);shell();}
    void shell(){root=new FrameLayout(this);root.addView(new Wave(this));LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setPadding(dp(11),dp(7),dp(11),0);
        LinearLayout hd=new LinearLayout(this);hd.setGravity(Gravity.CENTER_VERTICAL);hd.addView(new LedMark(this),new LinearLayout.LayoutParams(dp(42),dp(42)));title=tv("Salam Web Server",19,WHITE);title.setTypeface(null,1);hd.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));TextView m=tv("☰",31,WHITE);m.setGravity(Gravity.CENTER);m.setOnClickListener(v->menu());hd.addView(m,new LinearLayout.LayoutParams(dp(45),dp(52)));s.addView(hd);
        ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,0,0,dp(10));sc.addView(body);s.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(4),dp(4),dp(4),dp(4));nav.setBackground(gd(Color.rgb(3,17,33),Color.rgb(5,28,49),23));navItem(nav,"⌂","Home",HOME);navItem(nav,"▣","Files",FILES);navItem(nav,"≡","Logs",LOGS);navItem(nav,"⚙","Settings",SETTINGS);s.addView(nav,new LinearLayout.LayoutParams(-1,dp(74)));root.addView(s);setContentView(root);show(HOME);}
    void navItem(LinearLayout n,String ic,String name,int target){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);TextView i=tv(ic,24,target==screen?CYAN:MUTED);i.setGravity(Gravity.CENTER);x.addView(i,new LinearLayout.LayoutParams(-1,dp(31)));TextView t=tv(name,10,target==screen?CYAN:MUTED);t.setGravity(Gravity.CENTER);x.addView(t,new LinearLayout.LayoutParams(-1,dp(25)));x.setOnClickListener(v->show(target));n.addView(x,new LinearLayout.LayoutParams(0,dp(66),1));}
    void show(int s){screen=s;body.removeAllViews();if(s==HOME)home();else if(s==FILES)files();else if(s==LOGS)logs();else if(s==SETTINGS)settings();else if(s==NETWORK)network();else if(s==ABOUT)about();else browser();title.setText(s==HOME?"Salam Web Server":s==FILES?"Web Files":s==LOGS?"Server Logs":s==SETTINGS?"Server Settings":s==NETWORK?"Network Info":s==ABOUT?"About":"Browser Control Panel");}

    void home(){LinearLayout c=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView st=tv(WebServerService.running?"SERVER ONLINE":"SERVER OFFLINE",18,WebServerService.running?GREEN:RED);st.setTypeface(null,1);r.addView(st,new LinearLayout.LayoutParams(0,dp(52),1));r.addView(new ServerLights(this),new LinearLayout.LayoutParams(dp(160),dp(48)));c.addView(r);
        TextView url=tv(WebServerService.currentUrl(this),13,WHITE);url.setGravity(Gravity.CENTER_VERTICAL);url.setPadding(dp(14),0,dp(10),0);url.setBackground(gd(Color.rgb(3,18,35),Color.rgb(5,30,54),17));c.addView(url,new LinearLayout.LayoutParams(-1,dp(56)));
        LinearLayout a=new LinearLayout(this);Button o=btn("OPEN BROWSER"),cp=btn("COPY URL");a.addView(o,new LinearLayout.LayoutParams(0,dp(48),1));a.addView(cp,new LinearLayout.LayoutParams(0,dp(48),1));o.setOnClickListener(v->openBrowser());cp.setOnClickListener(v->copy(WebServerService.currentUrl(this)));c.addView(a);body.addView(c);
        LinearLayout mon=card();TextView mt=tv("",11,WHITE);mon.addView(mt);body.addView(mon);live(mt);
        Button toggle=btn(WebServerService.running?"■  STOP SERVER":"▶  START SERVER");toggle.setTextSize(14);toggle.setOnClickListener(v->toggle());body.addView(toggle,new LinearLayout.LayoutParams(-1,dp(54)));
        body.addView(section("QUICK ACTIONS"));LinearLayout a1=new LinearLayout(this);a1.addView(tile("📁","Web Files",()->show(FILES)),new LinearLayout.LayoutParams(0,dp(112),1));a1.addView(tile("⚙","Settings",()->show(SETTINGS)),new LinearLayout.LayoutParams(0,dp(112),1));body.addView(a1);LinearLayout a2=new LinearLayout(this);a2.addView(tile("🌐","Network",()->show(NETWORK)),new LinearLayout.LayoutParams(0,dp(112),1));a2.addView(tile("≡","Logs",()->show(LOGS)),new LinearLayout.LayoutParams(0,dp(112),1));body.addView(a2);
        body.addView(section("SERVER TOOLS"));row("▦","QR Server Sharing","Share active URL",()->qr());row("◎","Browser Control","Full browser-side server panel",()->browser());row("🔐","Security","Password, IP allow/block, rate limit",()->settings());row("◉","Live Monitor","Real-time server metrics",()->show(HOME));body.addView(section("DEVELOPER"));row("ⓘ","About","Salam Web Server 10.0",()->about());row("✉","Messenger","Contact developer",()->messenger());}
    void live(TextView v){Runnable x=new Runnable(){public void run(){if(v.getParent()==null)return;v.setText((WebServerService.running?"● ONLINE":"● OFFLINE")+"    Requests "+WebServerService.requests+"    Clients "+WebServerService.clients.size()+"\nUptime "+WebServerService.uptime()+"    RAM "+WebServerService.memoryText(MainActivity.this)+"\nCPU "+cpu()+"    Storage "+storage()+"\nInterface "+WebServerService.interfaceName(MainActivity.this)+"    IP "+WebServerService.localIp(MainActivity.this));h.postDelayed(this,1000);}};x.run();}
    LinearLayout tile(String ic,String n,Runnable r){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setBackground(gd(CARD,CARD2,22));TextView i=tv(ic,32,iconColor(n));i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(-1,dp(57)));TextView t=tv(n,12,WHITE);t.setTypeface(null,1);t.setGravity(Gravity.CENTER);c.addView(t,new LinearLayout.LayoutParams(-1,dp(35)));c.setOnClickListener(v->r.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(112),1);p.setMargins(dp(3),dp(3),dp(3),dp(3));c.setLayoutParams(p);return c;}
    void row(String ic,String n,String d,Runnable r){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);TextView i=tv(ic,27,iconColor(n));i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(dp(50),dp(56)));LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);TextView a=tv(n,15,WHITE);a.setTypeface(null,1);m.addView(a,new LinearLayout.LayoutParams(-1,dp(29)));m.addView(tv(d,10,MUTED),new LinearLayout.LayoutParams(-1,dp(22)));c.addView(m,new LinearLayout.LayoutParams(0,dp(56),1));TextView ar=tv("›",32,CYAN);ar.setGravity(Gravity.CENTER);c.addView(ar,new LinearLayout.LayoutParams(dp(30),dp(56)));c.setOnClickListener(v->r.run());body.addView(c);}
    int iconColor(String n){n=n.toLowerCase(Locale.US);if(n.contains("file"))return YELLOW;if(n.contains("setting"))return PURPLE;if(n.contains("network"))return CYAN;if(n.contains("log"))return ORANGE;if(n.contains("security"))return RED;if(n.contains("qr"))return GREEN;return CYAN;}

    void toggle(){boolean start=!WebServerService.running;toast(start?"Starting Server":"Stopping Server");server(start);h.postDelayed(()->{show(HOME);toast(WebServerService.running?"● Server Online":"● Server Offline");},1400);}
    void server(boolean start){try{Intent i=new Intent(this,WebServerService.class);i.setAction(start?"START":"STOP");if(start&&Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception e){toast(e.getMessage());}}

    void files(){body.addView(section("WEB FILE MANAGER"));LinearLayout ac=new LinearLayout(this);Button up=btn("＋ UPLOAD"),fo=btn("＋ FOLDER"),fi=btn("＋ FILE"),zp=btn("ZIP");ac.addView(up,new LinearLayout.LayoutParams(0,dp(43),1));ac.addView(fo,new LinearLayout.LayoutParams(0,dp(43),1));ac.addView(fi,new LinearLayout.LayoutParams(0,dp(43),1));ac.addView(zp,new LinearLayout.LayoutParams(0,dp(43),1));up.setOnClickListener(v->pick());fo.setOnClickListener(v->newFolder());fi.setOnClickListener(v->newFile());zp.setOnClickListener(v->zipDialog());body.addView(ac);body.addView(tv("Path: "+folder,11,MUTED));File d=new File(WebServerService.webRoot(this),folder);File[] fs=d.listFiles();if(fs==null){body.addView(tv("No files",12,MUTED));return;}Arrays.sort(fs,(x,y)->x.isDirectory()!=y.isDirectory()?(x.isDirectory()?-1:1):x.getName().compareToIgnoreCase(y.getName()));if(!folder.equals("/"))row("‹","..","Parent folder",()->{int k=folder.lastIndexOf('/');folder=k<=0?"/":folder.substring(0,k);show(FILES);});for(File f:fs)row(f.isDirectory()?"📁":"▤",f.getName(),f.isDirectory()?"Folder • "+count(f):fmt(f.length()),()->fileMenu(f));}
    int count(File f){File[]x=f.listFiles();return x==null?0:x.length;}String fmt(long b){if(b<1024)return b+" B";if(b<1048576)return b/1024+" KB";if(b<1073741824L)return b/1048576+" MB";return String.format(Locale.US,"%.1f GB",b/1073741824.0);}
    void fileMenu(File f){String[] a=f.isDirectory()?new String[]{"Open","Rename","Copy","Move","Delete"}:new String[]{"Edit","Rename","Copy","Move","ZIP","Save As","Delete"};new AlertDialog.Builder(this).setTitle(f.getName()).setItems(a,(d,w)->{String x=a[w];if(x.equals("Open")){folder=(folder.endsWith("/")?folder:folder+"/")+f.getName();show(FILES);}else if(x.equals("Edit"))edit(f);else if(x.equals("Rename"))rename(f);else if(x.equals("Copy")||x.equals("Move"))copyMove(f,x.equals("Move"));else if(x.equals("ZIP"))zipFile(f);else if(x.equals("Save As"))saveAs(f);else del(f);}).show();}
    void edit(File f){EditText e=input("");e.setGravity(Gravity.TOP);e.setMinLines(18);try{e.setText(read(f));}catch(Exception x){toast(x.getMessage());}new AlertDialog.Builder(this).setTitle("Editor • "+f.getName()).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{write(f,e.getText().toString());toast("Saved");}catch(Exception x){toast(x.getMessage());}}).show();}
    String read(File f)throws Exception{BufferedReader r=new BufferedReader(new FileReader(f));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x).append('\n');r.close();return s.toString();}void write(File f,String s)throws Exception{FileWriter w=new FileWriter(f);w.write(s);w.close();}
    void rename(File f){EditText e=input(f.getName());new AlertDialog.Builder(this).setTitle("Rename").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String n=e.getText().toString().trim().replace("/","_");if(n.length()>0&&!f.renameTo(new File(f.getParent(),n)))toast("Rename failed");show(FILES);}).show();}
    void copyMove(File f,boolean move){EditText e=input(folder);new AlertDialog.Builder(this).setTitle(move?"Move":"Copy").setView(e).setNegativeButton("Cancel",null).setPositiveButton(move?"Move":"Copy",(d,w)->{try{File dst=new File(WebServerService.webRoot(this),e.getText().toString());dst.mkdirs();copyRecursive(f,new File(dst,f.getName()));if(move)delete(f);toast(move?"Moved":"Copied");show(FILES);}catch(Exception x){toast(x.getMessage());}}).show();}
    void copyRecursive(File a,File b)throws IOException{if(a.isDirectory()){b.mkdirs();File[]z=a.listFiles();if(z!=null)for(File q:z)copyRecursive(q,new File(b,q.getName()));}else try(InputStream i=new FileInputStream(a);OutputStream o=new FileOutputStream(b)){byte[]z=new byte[16384];int n;while((n=i.read(z))>0)o.write(z,0,n);}}
    void del(File f){new AlertDialog.Builder(this).setTitle("Delete").setMessage("Delete "+f.getName()+"?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{delete(f);toast("Deleted");show(FILES);}).show();}
    void delete(File f){if(f.isDirectory()){File[]z=f.listFiles();if(z!=null)for(File q:z)delete(q);}f.delete();}
    void newFolder(){EditText e=input("new-folder");new AlertDialog.Builder(this).setTitle("New Folder").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{File f=new File(WebServerService.webRoot(this),folder+"/"+e.getText().toString().trim());toast(f.mkdirs()?"Folder created":"Could not create folder");show(FILES);}).show();}
    void newFile(){EditText e=input("index.html");new AlertDialog.Builder(this).setTitle("New File").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{try{File f=new File(WebServerService.webRoot(this),folder+"/"+e.getText().toString().trim());f.getParentFile().mkdirs();toast(f.createNewFile()?"File created":"Already exists");show(FILES);}catch(Exception x){toast(x.getMessage());}}).show();}
    void zipDialog(){EditText e=input("website.zip");new AlertDialog.Builder(this).setTitle("Create ZIP").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{try{zipDir(new File(WebServerService.webRoot(this),folder),new File(WebServerService.webRoot(this),folder+"/"+e.getText().toString().trim()));toast("ZIP created");show(FILES);}catch(Exception x){toast(x.getMessage());}}).show();}
    void zipFile(File f){try{File z=new File(f.getParent(),f.getName()+".zip");zipDir(f,z);toast("ZIP created: "+z.getName());show(FILES);}catch(Exception e){toast(e.getMessage());}}
    void zipDir(File src,File out)throws Exception{try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out))){if(src.isDirectory()){File[]fs=src.listFiles();if(fs!=null)for(File f:fs)zipRec(f,f.getName(),z);}else zipRec(src,src.getName(),z);}}
    void zipRec(File f,String name,ZipOutputStream z)throws Exception{if(f.isDirectory()){File[]fs=f.listFiles();if(fs==null)return;for(File x:fs)zipRec(x,name+"/"+x.getName(),z);}else{z.putNextEntry(new ZipEntry(name));try(InputStream i=new FileInputStream(f)){byte[]b=new byte[16384];int n;while((n=i.read(b))>0)z.write(b,0,n);}z.closeEntry();}}
    void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,101);}
    void saveAs(File f){pending=f;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_TITLE,f.getName());startActivityForResult(i,102);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);try{if(r==101&&c==RESULT_OK&&d!=null){if(d.getClipData()!=null)for(int i=0;i<d.getClipData().getItemCount();i++)copyUri(d.getClipData().getItemAt(i).getUri());else if(d.getData()!=null)copyUri(d.getData());toast("Upload complete");show(FILES);}else if(r==102&&c==RESULT_OK&&d!=null&&pending!=null){try(InputStream i=new FileInputStream(pending);OutputStream o=getContentResolver().openOutputStream(d.getData())){byte[]b=new byte[16384];int n;while((n=i.read(b))>0)o.write(b,0,n);}pending=null;toast("Saved");}}catch(Exception e){toast(e.getMessage());}}
    void copyUri(Uri u)throws Exception{String n="upload_"+System.currentTimeMillis();String p=u.getPath();if(p!=null&&p.contains(":"))n=p.substring(p.lastIndexOf(':')+1);n=n.replace("/","_");File out=new File(WebServerService.webRoot(this),folder+"/"+n);try(InputStream i=getContentResolver().openInputStream(u);OutputStream o=new FileOutputStream(out)){byte[]b=new byte[16384];int k;while((k=i.read(b))>0)o.write(b,0,k);}}

    void settings(){body.addView(section("SERVER ENGINE"));setting("⚙","Port",""+pref.getInt("port",8080),()->portDialog());setting("🚀","Auto Start",pref.getBoolean("autostart",false)?"Enabled":"Disabled",()->boolDialog("autostart","Auto Start"));setting("🌐","Network Mode","Wi-Fi → mobile data fallback",()->toast("All active interfaces are supported"));setting("↻","Restart","Restart HTTP engine",()->{server(false);h.postDelayed(()->server(true),500);});
        body.addView(section("SECURITY"));setting("🔐","Password Protection",pref.getBoolean("passwordOn",false)?"Enabled":"Disabled",()->passwordDialog());setting("🟢","IP Allowlist",pref.getString("allowIps","Empty"),()->ipDialog(false));setting("🔴","IP Blocklist",pref.getString("blockIps","Empty"),()->ipDialog(true));setting("⚡","Rate Limit",pref.getInt("rate",120)+" requests/min/IP",()->rateDialog());setting("👥","Maximum Clients",""+pref.getInt("maxClients",32),()->maxDialog());
        body.addView(section("SERVER TOOLS"));setting("▦","QR Sharing","Generate current URL",()->qr());setting("◎","Browser Control","Open control panel",()->browser());setting("🎨","Themes","Six animated themes",()->themeDialog());setting("🔔","Background Server","Foreground service + persistent notification",()->toast("Background server is managed by Android foreground service"));body.addView(section("SYSTEM"));Button stop=btn(WebServerService.running?"STOP SERVER":"START SERVER");stop.setOnClickListener(v->toggle());body.addView(stop,new LinearLayout.LayoutParams(-1,dp(52)));}
    void setting(String ic,String n,String d,Runnable r){row(ic,n,d,r);}
    void boolDialog(String key,String name){boolean v=pref.getBoolean(key,false);new AlertDialog.Builder(this).setTitle(name).setMessage("Current: "+(v?"ON":"OFF")).setNegativeButton("Cancel",null).setPositiveButton(v?"Disable":"Enable",(d,w)->{pref.edit().putBoolean(key,!v).apply();toast(name+(!v?" enabled":" disabled"));show(SETTINGS);}).show();}
    void portDialog(){EditText e=input(""+pref.getInt("port",8080));dialog("Server Port",e,x->{try{int p=Integer.parseInt(x);if(p<1024||p>65535)throw new Exception();pref.edit().putInt("port",p).apply();toast("Port saved");show(SETTINGS);}catch(Exception z){toast("Port must be 1024–65535");}});}
    void rateDialog(){EditText e=input(""+pref.getInt("rate",120));dialog("Rate limit (0=unlimited)",e,x->{try{pref.edit().putInt("rate",Math.max(0,Integer.parseInt(x))).apply();show(SETTINGS);}catch(Exception z){toast("Invalid value");}});}
    void maxDialog(){EditText e=input(""+pref.getInt("maxClients",32));dialog("Maximum clients",e,x->{try{pref.edit().putInt("maxClients",Math.max(1,Integer.parseInt(x))).apply();show(SETTINGS);}catch(Exception z){toast("Invalid value");}});}
    void passwordDialog(){EditText e=input("");e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);e.setHint("Minimum 4 characters");dialog("Web Login Password",e,x->{if(x.length()<4){toast("Minimum 4 characters");return;}pref.edit().putString("password",x).putBoolean("passwordOn",true).apply();toast("Password enabled");show(SETTINGS);});}
    void ipDialog(boolean block){String key=block?"blockIps":"allowIps";EditText e=input(pref.getString(key,""));e.setHint("IP1,IP2,IP3");dialog(block?"IP Blocklist":"IP Allowlist",e,x->{pref.edit().putString(key,x).apply();toast("IP list saved");show(SETTINGS);});}
    void dialog(String t,EditText e,Save s){new AlertDialog.Builder(this).setTitle(t).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->s.go(e.getText().toString().trim())).show();}
    interface Save{void go(String x);}
    void network(){body.addView(section("NETWORK / INTERFACES"));row("📶","Wi-Fi IP",WebServerService.wifiIp(this),()->copy(WebServerService.wifiIp(this)));row("📡","Mobile Data IP",WebServerService.cellularIp(this),()->copy(WebServerService.cellularIp(this)));row("◎","Active Server URL",WebServerService.currentUrl(this),()->copy(WebServerService.currentUrl(this)));row("▤","Active Interface",WebServerService.interfaceName(this),()->toast(WebServerService.networkInfo(this)));row("⌁","Gateway / DNS","Detected from active network",()->toast(WebServerService.networkInfo(this)));body.addView(section("SERVER MACHINE"));body.addView(tv("Binding: 0.0.0.0\nWi-Fi: automatic LAN URL\nMobile Data: automatic cellular-interface URL\nCarrier NAT may prevent inbound mobile-data connections.",11,MUTED));}
    void logs(){LinearLayout a=new LinearLayout(this);Button c=btn("CLEAR LOG"),r=btn("REFRESH");a.addView(c,new LinearLayout.LayoutParams(0,dp(44),1));a.addView(r,new LinearLayout.LayoutParams(0,dp(44),1));c.setOnClickListener(v->{WebServerService.clearLogs();show(LOGS);});r.setOnClickListener(v->show(LOGS));body.addView(a);TextView l=tv(WebServerService.logsText(),10,WHITE);l.setTypeface(Typeface.MONOSPACE);l.setPadding(dp(10),dp(10),dp(10),dp(10));l.setBackground(gd(PANEL(),CARD,15));body.addView(l);}
    int PANEL(){return Color.rgb(3,20,39);}
    void about(){LinearLayout c=card();c.setGravity(Gravity.CENTER);c.addView(tv("▰",42,CYAN));c.addView(tv("Salam Web Server",22,WHITE));c.addView(tv("Version 10.0 • Android Local Web Server",11,MUTED));body.addView(c);body.addView(section("DEVELOPER"));row("ⓘ","Abdus Salam","09696590864",()->toast("salam230864@gmail.com"));row("✉","Email","salam230864@gmail.com",()->email());row("ⓜ","Messenger","m.me/Salam.864",()->messenger());}
    void browser(){body.addView(section("BROWSER CONTROL PANEL"));LinearLayout c=card();c.setGravity(Gravity.CENTER);c.addView(tv(WebServerService.running?"● ONLINE":"● OFFLINE",14,WebServerService.running?GREEN:RED));c.addView(tv("Salam Web Server",25,WHITE));c.addView(tv(WebServerService.currentUrl(this),11,MUTED));body.addView(c);Button o=btn("OPEN SERVER");o.setOnClickListener(v->openBrowser());body.addView(o);row("▣","View Files","Hosted web root",()->openBrowser());row("📊","Server Info","Live JSON information",()->show(NETWORK));row("≡","Live Logs","Request history",()->show(LOGS));row("⚙","Settings","Full configuration",()->show(SETTINGS));}
    void qr(){if(!WebServerService.running){toast("Start server first");return;}String u=WebServerService.currentUrl(this);new AlertDialog.Builder(this).setTitle("QR Server Sharing").setMessage(u+"\n\nScan this URL from another device on the same reachable network.").setPositiveButton("Share",(d,w)->share(u)).setNegativeButton("Close",null).show();}
    void themeDialog(){String[]a={"Electric Blue","Cyan Night","Purple Neon","Emerald","Amber","Ocean"};new AlertDialog.Builder(this).setTitle("Theme").setSingleChoiceItems(a,pref.getInt("theme",0),(d,w)->{pref.edit().putInt("theme",w).apply();d.dismiss();shell();});}
    void menu(){new AlertDialog.Builder(this).setTitle("Salam Web Server").setItems(new String[]{"Home","Files","Network","Logs","Settings","About","Browser Control"},(d,w)->show(new int[]{HOME,FILES,NETWORK,LOGS,SETTINGS,ABOUT,BROWSER}[w])).show();}
    void copy(String s){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Server URL",s));toast("Copied");}
    void openBrowser(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(WebServerService.currentUrl(this))));}catch(Exception e){toast("Browser unavailable");}}
    void share(String s){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,s);startActivity(Intent.createChooser(i,"Share URL"));}
    void messenger(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://m.me/Salam.864")));}catch(Exception e){toast("Messenger unavailable");}}
    void email(){try{startActivity(new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:salam230864@gmail.com")));}catch(Exception e){toast("Email unavailable");}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    String storage(){StatFs s=new StatFs(getFilesDir().getAbsolutePath());return fmt(s.getTotalBytes()-s.getAvailableBytes())+" / "+fmt(s.getTotalBytes());}
    String cpu(){try{BufferedReader r=new BufferedReader(new FileReader("/proc/stat"));String x=r.readLine();r.close();String[]a=x.trim().split("\\s+");long u=Long.parseLong(a[1]),n=Long.parseLong(a[2]),sy=Long.parseLong(a[3]),id=Long.parseLong(a[4]),tot=u+n+sy+id,busy=tot-id,ot=pref.getLong("ct",-1),ob=pref.getLong("cb",-1);pref.edit().putLong("ct",tot).putLong("cb",busy).apply();return ot>0&&tot>ot?String.format(Locale.US,"%.0f%%",100.0*(busy-ob)/(double)(tot-ot)):"0%";}catch(Exception e){return"—";}}

    class ServerLights extends View{Paint p=new Paint(1);ValueAnimator pulse;long start=0;ServerLights(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);pulse=ValueAnimator.ofFloat(.25f,1f,.25f);pulse.setDuration(900);pulse.setRepeatCount(ValueAnimator.INFINITE);pulse.addUpdateListener(v->invalidate());pulse.start();}protected void onDraw(Canvas c){boolean on=WebServerService.running;if(on&&start==0)start=System.currentTimeMillis();if(!on)start=0;int active=on?Math.min(7,(int)((System.currentTimeMillis()-start)/240)+1):0;float pval=(Float)pulse.getAnimatedValue();for(int i=0;i<7;i++){float x=dp(7+i*21),y=getHeight()/2f;int col=on&&i<active?LED[i]:RED;float glow=on&&i<active?dp(10)*pval:dp(3)*pval;p.setColor(col);p.setShadowLayer(glow,0,0,col);c.drawCircle(x,y,dp(5),p);p.clearShadowLayer();}postInvalidateDelayed(50);}}
    class LedMark extends View{Paint p=new Paint(1);LedMark(Context c){super(c);}protected void onDraw(Canvas c){p.setColor(CYAN);p.setShadowLayer(dp(8),0,0,CYAN);c.drawCircle(dp(21),dp(21),dp(13),p);p.clearShadowLayer();}}
    static class Wave extends View{Paint p=new Paint(1);Path q=new Path();Wave(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight(),th=getContext().getSharedPreferences("server",MODE_PRIVATE).getInt("theme",0);int a=BG,b=CARD,line=BLUE;if(th==1){b=Color.rgb(4,52,72);line=CYAN;}else if(th==2){a=Color.rgb(12,4,28);b=Color.rgb(48,10,78);line=PURPLE;}else if(th==3){a=Color.rgb(2,22,18);b=Color.rgb(5,62,48);line=GREEN;}else if(th==4){a=Color.rgb(30,9,3);b=Color.rgb(76,28,7);line=ORANGE;}else if(th==5){a=Color.rgb(3,8,28);b=Color.rgb(13,39,82);line=Color.rgb(72,135,255);}p.setShader(new LinearGradient(0,0,w,h,a,b,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setColor(line);p.setStrokeWidth(1.3f);for(int j=0;j<4;j++){q.reset();for(int x=0;x<=w;x+=10){float y=h*.75f+j*17+(float)Math.sin(x*.013+j)*17;if(x==0)q.moveTo(x,y);else q.lineTo(x,y);}c.drawPath(q,p);}p.setStyle(Paint.Style.FILL);}}
}
