package com.salam.androidwebserver;

import android.Manifest;
import android.animation.ValueAnimator;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.*;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.zip.*;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;

public class MainActivity extends Activity {
    static final int BG=Color.rgb(3,12,25), SURFACE=Color.rgb(7,27,51), SURFACE2=Color.rgb(9,35,65);
    static final int PANEL=Color.rgb(4,20,39), BLUE=Color.rgb(10,139,255), CYAN=Color.rgb(28,211,255);
    static final int GREEN=Color.rgb(18,232,166), RED=Color.rgb(255,70,82), WHITE=Color.rgb(247,250,255), MUTED=Color.rgb(157,183,213);
    static final int[] STATUS_COLORS={GREEN,CYAN,Color.rgb(170,88,255),Color.rgb(255,205,40),WHITE,Color.rgb(255,140,35),RED};
    static final int HOME=1,FILES=2,SETTINGS=3,NETWORK=4,LOGS=5,ABOUT=6,BROWSER=7;
    SharedPreferences pref; FrameLayout root; LinearLayout body; TextView title; Handler handler=new Handler(Looper.getMainLooper());
    int screen=HOME; String folder="/"; File pending; boolean splashDone=false;

    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
    GradientDrawable bg(int a,int b,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}
    GradientDrawable stroke(int fill,int line,float r){GradientDrawable g=bg(fill,fill,r);g.setStroke(dp(1),line);return g;}
    void margin(View v,int l,int t,int r,int b){ViewGroup.MarginLayoutParams p=(ViewGroup.MarginLayoutParams)v.getLayoutParams();p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);}
    ImageView icon(int res,int size){ImageView i=new ImageView(this);i.setImageResource(res);i.setColorFilter(WHITE);i.setScaleType(ImageView.ScaleType.CENTER_INSIDE);i.setPadding(dp(5),dp(5),dp(5),dp(5));i.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));return i;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(WHITE);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setPadding(dp(8),0,dp(8),0);b.setBackground(bg(BLUE,CYAN,22));return b;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(SURFACE,SURFACE2,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));c.setLayoutParams(p);return c;}
    TextView label(String s){TextView v=text(s,11,Color.rgb(121,177,232));v.setTypeface(null,1);v.setLetterSpacing(.04f);v.setPadding(dp(10),dp(8),0,dp(5));return v;}

    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);pref=getSharedPreferences("server",MODE_PRIVATE);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);splash();}
    void splash(){root=new FrameLayout(this);root.setBackgroundColor(BG);root.addView(new Wave(this));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(30),0,dp(30),0);Space a=new Space(this);c.addView(a,new LinearLayout.LayoutParams(1,0,1));ImageView logo=icon(com.salam.androidwebserver.R.drawable.ic_server,82);logo.setColorFilter(CYAN);c.addView(logo,new LinearLayout.LayoutParams(-1,dp(90)));TextView n=text("Salam",38,BLUE);n.setTypeface(null,1);n.setGravity(Gravity.CENTER);c.addView(n,new LinearLayout.LayoutParams(-1,dp(50)));TextView w=text("Web Server",28,WHITE);w.setTypeface(null,1);w.setGravity(Gravity.CENTER);c.addView(w,new LinearLayout.LayoutParams(-1,dp(42)));TextView sub=text("FAST  •  SECURE  •  LOCAL",11,MUTED);sub.setGravity(Gravity.CENTER);c.addView(sub,new LinearLayout.LayoutParams(-1,dp(40)));TextView dev=text("Abdus Salam  •  Version 10.0",11,MUTED);dev.setGravity(Gravity.CENTER);c.addView(dev,new LinearLayout.LayoutParams(-1,dp(42)));Space z=new Space(this);c.addView(z,new LinearLayout.LayoutParams(1,0,1));root.addView(c,new FrameLayout.LayoutParams(-1,-1));setContentView(root);handler.postDelayed(()->{if(!isFinishing()){splashDone=true;appShell();}},700);}

    void appShell(){root=new FrameLayout(this);root.setBackgroundColor(BG);root.addView(new Wave(this));LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(12),0,dp(12),0);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);ImageView mark=icon(R.drawable.ic_server,34);mark.setColorFilter(CYAN);head.addView(mark);title=text("Salam Web Server",18,WHITE);title.setTypeface(null,1);title.setGravity(Gravity.CENTER_VERTICAL);head.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));TextView menu=text("☰",29,WHITE);menu.setGravity(Gravity.CENTER);menu.setOnClickListener(v->menuDialog());head.addView(menu,new LinearLayout.LayoutParams(dp(46),dp(56)));shell.addView(head,new LinearLayout.LayoutParams(-1,dp(58)));
        body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setClipToPadding(false);sc.setPadding(0,0,0,dp(8));sc.addView(body);shell.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setBackground(bg(Color.rgb(3,17,32),Color.rgb(5,25,46),22));addNav(nav,R.drawable.ic_dashboard,"Home",HOME);addNav(nav,R.drawable.ic_folder,"Files",FILES);addNav(nav,R.drawable.ic_log,"Logs",LOGS);addNav(nav,R.drawable.ic_settings,"Settings",SETTINGS);shell.addView(nav,new LinearLayout.LayoutParams(-1,dp(72)));root.addView(shell);setContentView(root);show(HOME);}
    void addNav(LinearLayout nav,int res,String name,int target){LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setGravity(Gravity.CENTER);ImageView i=icon(res,24);i.setColorFilter(target==screen?CYAN:MUTED);n.addView(i,new LinearLayout.LayoutParams(-1,dp(28)));TextView t=text(name,10,target==screen?CYAN:MUTED);t.setGravity(Gravity.CENTER);n.addView(t,new LinearLayout.LayoutParams(-1,dp(24)));n.setOnClickListener(v->show(target));nav.addView(n,new LinearLayout.LayoutParams(0,dp(68),1));}
    void show(int s){screen=s;body.removeAllViews();if(s==HOME)home();else if(s==FILES)files();else if(s==SETTINGS)settings();else if(s==NETWORK)network();else if(s==LOGS)logs();else if(s==ABOUT)aboutPage();else browserPage();title.setText(s==HOME?"Salam Web Server":s==FILES?"Web Files":s==SETTINGS?"Server Settings":s==NETWORK?"Network Info":s==LOGS?"Server Logs":s==ABOUT?"About":"Web Preview");}

    void home(){
        LinearLayout status=card();LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView st=text(WebServerService.running?"Server Running":"Server Stopped",18,WebServerService.running?GREEN:RED);st.setTypeface(null,1);row.addView(st,new LinearLayout.LayoutParams(0,dp(42),1));StatusLights lights=new StatusLights(this);row.addView(lights,new LinearLayout.LayoutParams(dp(128),dp(40)));status.addView(row);
        TextView url=text(WebServerService.currentUrl(this),14,WHITE);url.setGravity(Gravity.CENTER_VERTICAL);url.setPadding(dp(14),0,dp(10),0);url.setBackground(bg(PANEL,Color.rgb(5,25,46),16));status.addView(url,new LinearLayout.LayoutParams(-1,dp(56)));
        LinearLayout actions=new LinearLayout(this);Button open=button("Open Browser"),copy=button("Copy URL");actions.addView(open,new LinearLayout.LayoutParams(0,dp(48),1));actions.addView(copy,new LinearLayout.LayoutParams(0,dp(48),1));open.setOnClickListener(v->{openBrowser();});copy.setOnClickListener(v->copyUrl());status.addView(actions);body.addView(status);
        LinearLayout metrics=card();metrics.setPadding(dp(14),dp(8),dp(14),dp(8));TextView m=text("",11,WHITE);m.setLineSpacing(2,1);metrics.addView(m);body.addView(metrics);updateMetrics(m);
        Button toggle=button(WebServerService.running?"■  Stop Server":"▶  Start Server");toggle.setOnClickListener(v->{server(!WebServerService.running);toast(WebServerService.running?"Server started":"Starting server…");handler.postDelayed(()->show(HOME),500);});body.addView(toggle,new LinearLayout.LayoutParams(-1,dp(48)));
        body.addView(label("QUICK ACTIONS"));LinearLayout g1=new LinearLayout(this);g1.addView(tile(R.drawable.ic_folder,"Web Files",()->show(FILES)),new LinearLayout.LayoutParams(0,dp(116),1));g1.addView(tile(R.drawable.ic_settings,"Settings",()->show(SETTINGS)),new LinearLayout.LayoutParams(0,dp(116),1));body.addView(g1);LinearLayout g2=new LinearLayout(this);g2.addView(tile(R.drawable.ic_network,"Network Info",()->show(NETWORK)),new LinearLayout.LayoutParams(0,dp(116),1));g2.addView(tile(R.drawable.ic_log,"Server Logs",()->show(LOGS)),new LinearLayout.LayoutParams(0,dp(116),1));body.addView(g2);
        body.addView(label("SERVER"));rowTile(R.drawable.ic_qr,"QR Server Sharing","Share your active URL",()->qr());rowTile(R.drawable.ic_globe,"Web Preview","Browser-side server dashboard",()->browserPage());rowTile(R.drawable.ic_security,"Security","Password • IP rules • rate limit",()->security());rowTile(R.drawable.ic_refresh,"Live Dashboard","Auto-refresh server monitor",()->show(HOME));
        body.addView(label("DEVELOPER"));rowTile(R.drawable.ic_info,"About","Salam Web Server 10.0",()->show(ABOUT));rowTile(R.drawable.ic_message,"Messenger","Contact developer",()->messenger());
    }
    void updateMetrics(TextView m){String ip=WebServerService.localIp(this);m.setText((WebServerService.running?"● Online":"● Offline")+"     Requests: "+WebServerService.requests+"     Clients: "+WebServerService.clients.size()+"\nUptime: "+WebServerService.uptime()+"     RAM: "+WebServerService.memoryText(this)+"\nCPU: "+cpuUsage()+"     Storage: "+storageText()+"\nNetwork: "+WebServerService.interfaceName(this)+"  •  "+ip);}
    View tile(int res,String name,Runnable r){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(8),dp(8),dp(8),dp(8));c.setBackground(bg(SURFACE,SURFACE2,22));ImageView i=icon(res,42);c.addView(i);TextView n=text(name,12,WHITE);n.setGravity(Gravity.CENTER);n.setTypeface(null,1);c.addView(n,new LinearLayout.LayoutParams(-1,dp(28)));c.setOnClickListener(v->r.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(116),1);p.setMargins(dp(3),dp(4),dp(3),dp(4));c.setLayoutParams(p);return c;}
    void rowTile(int res,String name,String desc,Runnable r){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);ImageView i=icon(res,42);c.addView(i);LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);TextView n=text(name,15,WHITE);n.setTypeface(null,1);mid.addView(n,new LinearLayout.LayoutParams(-1,dp(28)));mid.addView(text(desc,10,MUTED),new LinearLayout.LayoutParams(-1,dp(20)));c.addView(mid,new LinearLayout.LayoutParams(0,dp(52),1));TextView a=text("›",32,CYAN);a.setGravity(Gravity.CENTER);c.addView(a,new LinearLayout.LayoutParams(dp(28),dp(52)));c.setOnClickListener(v->r.run());body.addView(c);}

    void files(){body.addView(label("WEB FILES"));LinearLayout search=card();EditText q=input("");q.setHint("Search files…");q.setSingleLine(true);q.setHintTextColor(MUTED);q.setTextColor(WHITE);q.setBackground(bg(PANEL,Color.rgb(5,25,46),16));search.addView(q,new LinearLayout.LayoutParams(-1,dp(48)));body.addView(search);LinearLayout act=new LinearLayout(this);Button up=button("＋ Upload"),fo=button("＋ Folder"),fi=button("＋ File");act.addView(up,new LinearLayout.LayoutParams(0,dp(43),1));act.addView(fo,new LinearLayout.LayoutParams(0,dp(43),1));act.addView(fi,new LinearLayout.LayoutParams(0,dp(43),1));up.setOnClickListener(v->pick());fo.setOnClickListener(v->newFolder());fi.setOnClickListener(v->newFile());body.addView(act);TextView path=text("/  "+folder,11,MUTED);path.setPadding(dp(10),dp(8),0,0);body.addView(path,new LinearLayout.LayoutParams(-1,dp(34)));
        File dir=new File(WebServerService.webRoot(this),folder);File[] list=dir.listFiles();if(list==null){body.addView(text("No files yet.",12,MUTED));return;}Arrays.sort(list,(a,b)->a.isDirectory()!=b.isDirectory()?(a.isDirectory()?-1:1):a.getName().compareToIgnoreCase(b.getName()));if(!"/".equals(folder))rowTile(R.drawable.ic_folder,"..","Parent folder",()->{int x=folder.lastIndexOf('/');folder=x<=0?"/":folder.substring(0,x);show(FILES);});
        for(File f:list){if(q.getText().length()>0&&!f.getName().toLowerCase(Locale.US).contains(q.getText().toString().toLowerCase(Locale.US)))continue;rowTile(f.isDirectory()?R.drawable.ic_folder:fileRes(f.getName()),f.getName(),f.isDirectory()?"Folder • "+count(f)+" items":format(f.length()),()->fileMenu(f));}
        q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){show(FILES);}public void afterTextChanged(android.text.Editable e){}});
    }
    int fileRes(String n){String x=n.toLowerCase(Locale.US);if(x.endsWith(".zip"))return R.drawable.ic_file;if(x.endsWith(".html")||x.endsWith(".htm"))return R.drawable.ic_globe;if(x.endsWith(".json"))return R.drawable.ic_file;if(x.endsWith(".png")||x.endsWith(".jpg")||x.endsWith(".jpeg")||x.endsWith(".webp"))return R.drawable.ic_file;return R.drawable.ic_file;}
    int count(File f){File[] x=f.listFiles();return x==null?0:x.length;}String format(long b){if(b<1024)return b+" B";if(b<1048576)return(b/1024)+" KB";if(b<1073741824L)return(b/1048576)+" MB";return String.format(Locale.US,"%.1f GB",b/1073741824.0);}
    EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(WHITE);e.setTextSize(14);e.setPadding(dp(12),0,dp(12),0);return e;}
    void fileMenu(File f){ArrayList<String> a=new ArrayList<>();if(f.isDirectory())a.add("Open folder");else{a.add("Edit file");if(f.getName().toLowerCase(Locale.US).endsWith(".zip"))a.add("Extract ZIP");}a.add("Rename");a.add("Copy");a.add("Move");a.add("Save As");a.add("Delete");new AlertDialog.Builder(this).setTitle(f.getName()).setItems(a.toArray(new String[0]),(d,w)->{String s=a.get(w);if(s.equals("Open folder")){folder=(folder.endsWith("/")?folder:folder+"/")+f.getName();show(FILES);}else if(s.equals("Edit file"))edit(f);else if(s.equals("Extract ZIP"))extractZip(f);else if(s.equals("Rename"))rename(f);else if(s.equals("Copy"))copyMove(f,false);else if(s.equals("Move"))copyMove(f,true);else if(s.equals("Save As"))saveAs(f);else deleteConfirm(f);}).show();}
    void edit(File f){EditText e=input("");e.setGravity(Gravity.TOP);e.setMinLines(18);try{e.setText(read(f));}catch(Exception x){toast(x.getMessage());}new AlertDialog.Builder(this).setTitle("Edit • "+f.getName()).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{write(f,e.getText().toString());toast("File saved");}catch(Exception x){toast(x.getMessage());}}).show();}
    String read(File f)throws Exception{BufferedReader r=new BufferedReader(new FileReader(f));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x).append('\n');r.close();return s.toString();}void write(File f,String s)throws Exception{FileWriter w=new FileWriter(f);w.write(s);w.close();}
    void rename(File f){EditText e=input(f.getName());new AlertDialog.Builder(this).setTitle("Rename").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Rename",(d,w)->{String n=e.getText().toString().trim().replace("/","_");if(!n.isEmpty()){if(!f.renameTo(new File(f.getParent(),n)))toast("Rename failed");show(FILES);}}).show();}
    void copyMove(File f,boolean move){EditText e=input(folder);new AlertDialog.Builder(this).setTitle(move?"Move":"Copy").setView(e).setNegativeButton("Cancel",null).setPositiveButton(move?"Move":"Copy",(d,w)->{try{File dir=new File(WebServerService.webRoot(this),e.getText().toString());dir.mkdirs();copyRecursive(f,new File(dir,f.getName()));if(move)delete(f);show(FILES);toast(move?"Moved":"Copied");}catch(Exception x){toast(x.getMessage());}}).show();}
    void copyRecursive(File a,File b)throws IOException{if(a.isDirectory()){b.mkdirs();File[] z=a.listFiles();if(z!=null)for(File q:z)copyRecursive(q,new File(b,q.getName()));}else{try(InputStream i=new FileInputStream(a);OutputStream o=new FileOutputStream(b)){byte[] z=new byte[16384];int n;while((n=i.read(z))>0)o.write(z,0,n);}}}
    void deleteConfirm(File f){new AlertDialog.Builder(this).setTitle("Delete").setMessage("Delete "+f.getName()+" permanently?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{delete(f);show(FILES);toast("Deleted");}).show();}void delete(File f){if(f.isDirectory()){File[] z=f.listFiles();if(z!=null)for(File q:z)delete(q);}f.delete();}
    void newFolder(){EditText e=input("new-folder");new AlertDialog.Builder(this).setTitle("Create Folder").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{File f=new File(WebServerService.webRoot(this),folder+"/"+e.getText().toString().trim());if(f.mkdirs())toast("Folder created");else toast("Could not create folder");show(FILES);}).show();}
    void newFile(){EditText e=input("index.html");new AlertDialog.Builder(this).setTitle("Create File").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{try{File f=new File(WebServerService.webRoot(this),folder+"/"+e.getText().toString().trim());f.getParentFile().mkdirs();if(f.createNewFile())toast("File created");show(FILES);}catch(Exception x){toast(x.getMessage());}}).show();}
    void extractZip(File zip){new AlertDialog.Builder(this).setTitle("Extract ZIP").setMessage("Extract into current folder?").setNegativeButton("Cancel",null).setPositiveButton("Extract",(d,w)->{try{unzip(zip,new File(WebServerService.webRoot(this),folder));toast("ZIP extracted");show(FILES);}catch(Exception x){toast(x.getMessage());}}).show();}
    void unzip(File zip,File dest)throws Exception{String base=dest.getCanonicalPath();try(ZipInputStream in=new ZipInputStream(new FileInputStream(zip))){ZipEntry e;byte[] buf=new byte[16384];while((e=in.getNextEntry())!=null){File out=new File(dest,e.getName());String cp=out.getCanonicalPath();if(!cp.equals(base)&&!cp.startsWith(base+File.separator))throw new SecurityException("Unsafe ZIP path");if(e.isDirectory())out.mkdirs();else{out.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(out)){int n;while((n=in.read(buf))>0)o.write(buf,0,n);}}}}}
    void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,101);}void saveAs(File f){pending=f;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_TITLE,f.getName());startActivityForResult(i,102);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);try{if(r==101&&c==RESULT_OK&&d!=null){if(d.getClipData()!=null)for(int k=0;k<d.getClipData().getItemCount();k++)copyUri(d.getClipData().getItemAt(k).getUri());else if(d.getData()!=null)copyUri(d.getData());show(FILES);toast("Upload complete");}else if(r==102&&c==RESULT_OK&&d!=null&&d.getData()!=null&&pending!=null){try(InputStream i=new FileInputStream(pending);OutputStream o=getContentResolver().openOutputStream(d.getData())){byte[] z=new byte[16384];int n;while((n=i.read(z))>0)o.write(z,0,n);}pending=null;toast("Saved");}}catch(Exception e){toast(e.getMessage());}}
    void copyUri(Uri u)throws Exception{String n="upload_"+System.currentTimeMillis();String p=u.getPath();if(p!=null&&p.contains(":"))n=p.substring(p.lastIndexOf(':')+1);if(n.contains("/"))n=n.substring(n.lastIndexOf('/')+1);n=n.replace("/","_");File out=new File(WebServerService.webRoot(this),folder+"/"+n);try(InputStream i=getContentResolver().openInputStream(u);OutputStream o=new FileOutputStream(out)){byte[] z=new byte[16384];int k;while((k=i.read(z))>0)o.write(z,0,k);}}

    void settings(){body.addView(label("SERVER CONFIGURATION"));settingRow(R.drawable.ic_settings,"Port",""+pref.getInt("port",8080),()->portDialog());settingRow(R.drawable.ic_folder,"Document Root",WebServerService.webRoot(this).getAbsolutePath(),()->toast(WebServerService.webRoot(this).getAbsolutePath()));settingSwitch(R.drawable.ic_play,"Auto Start","Start server when the app opens","autostart");settingRow(R.drawable.ic_wifi,"Network Mode","Auto: Wi‑Fi first • Mobile data fallback",()->toast("Server binds to 0.0.0.0 on all interfaces"));body.addView(label("SECURITY"));settingSwitch(R.drawable.ic_network,"Allow Local Network","Allow devices on detected LAN interface","allowNetwork");settingSwitchAction(R.drawable.ic_lock,"Password Protection","Protect browser access with Basic Auth","passwordOn",()->passwordDialog());settingRow(R.drawable.ic_security,"IP Allowlist","Selected IP addresses only",()->ipList(false));settingRow(R.drawable.ic_delete,"IP Blocklist","Blocked client IP addresses",()->ipList(true));settingRow(R.drawable.ic_refresh,"Request Rate Limit",""+pref.getInt("rate",120)+" requests/min/IP",()->rateDialog());settingRow(R.drawable.ic_dashboard,"Maximum Clients",""+pref.getInt("maxClients",32),()->maxClientsDialog());body.addView(label("ADVANCED"));settingRow(R.drawable.ic_qr,"QR Server Sharing","Generate QR for current URL",()->qr());settingRow(R.drawable.ic_globe,"Browser Control Panel","Open server dashboard in browser",()->browserPage());settingRow(R.drawable.ic_refresh,"Auto Refresh","Live dashboard refresh every second",()->toast("Live monitoring is active"));settingRow(R.drawable.ic_settings,"Themes","Blue • Cyan • Purple • Green • Amber • Ocean",()->themeDialog());Button save=button("Save Changes");save.setOnClickListener(v->toast("Settings saved"));body.addView(save,new LinearLayout.LayoutParams(-1,dp(50)));}
    void settingRow(int res,String name,String value,Runnable r){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);ImageView i=icon(res,44);c.addView(i);LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);TextView n=text(name,15,WHITE);n.setTypeface(null,1);mid.addView(n,new LinearLayout.LayoutParams(-1,dp(27)));TextView v=text(value,10,MUTED);mid.addView(v,new LinearLayout.LayoutParams(-1,dp(20)));c.addView(mid,new LinearLayout.LayoutParams(0,dp(50),1));TextView a=text("›",30,CYAN);a.setGravity(Gravity.CENTER);c.addView(a,new LinearLayout.LayoutParams(dp(26),dp(50)));c.setOnClickListener(v->r.run());body.addView(c);}
    void settingSwitch(int res,String name,String desc,String key){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.addView(icon(res,44));LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);m.addView(text(name,15,WHITE),new LinearLayout.LayoutParams(-1,dp(28)));m.addView(text(desc,10,MUTED),new LinearLayout.LayoutParams(-1,dp(20)));c.addView(m,new LinearLayout.LayoutParams(0,dp(50),1));Switch sw=new Switch(this);sw.setChecked(pref.getBoolean(key,false));sw.setOnCheckedChangeListener((b,v)->{pref.edit().putBoolean(key,v).apply();toast(name+(v?" enabled":" disabled"));});c.addView(sw,new LinearLayout.LayoutParams(dp(54),dp(50)));body.addView(c);}
    void settingSwitchAction(int res,String name,String desc,String key,Runnable action){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.addView(icon(res,44));LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);m.addView(text(name,15,WHITE),new LinearLayout.LayoutParams(-1,dp(28)));m.addView(text(desc,10,MUTED),new LinearLayout.LayoutParams(-1,dp(20)));c.addView(m,new LinearLayout.LayoutParams(0,dp(50),1));Switch sw=new Switch(this);sw.setChecked(pref.getBoolean(key,false));sw.setOnCheckedChangeListener((b,v)->{pref.edit().putBoolean(key,v).apply();if(v)action.run();else{pref.edit().remove("password").apply();toast("Password protection disabled");}});c.addView(sw,new LinearLayout.LayoutParams(dp(54),dp(50)));body.addView(c);}
    void passwordDialog(){EditText e=input("");e.setHint("New password");e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Web Password").setMessage("Browser login username: admin").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String p=e.getText().toString();if(p.length()<4){toast("Use at least 4 characters");pref.edit().putBoolean("passwordOn",false).apply();return;}pref.edit().putString("password",p).putBoolean("passwordOn",true).apply();toast("Password updated");}).show();}
    void portDialog(){EditText e=input(""+pref.getInt("port",8080));new AlertDialog.Builder(this).setTitle("Server Port").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{int p=Integer.parseInt(e.getText().toString());if(p<1024||p>65535)throw new Exception("Port must be 1024–65535");pref.edit().putInt("port",p).apply();toast("Port saved: "+p);}catch(Exception x){toast(x.getMessage());}}).show();}
    void rateDialog(){EditText e=input(""+pref.getInt("rate",120));new AlertDialog.Builder(this).setTitle("Request Rate Limit").setMessage("0 = unlimited").setView(e).setPositiveButton("Save",(d,w)->{try{pref.edit().putInt("rate",Math.max(0,Integer.parseInt(e.getText().toString()))).apply();show(SETTINGS);}catch(Exception x){toast("Invalid number");}}).setNegativeButton("Cancel",null).show();}
    void maxClientsDialog(){EditText e=input(""+pref.getInt("maxClients",32));new AlertDialog.Builder(this).setTitle("Maximum Clients").setView(e).setPositiveButton("Save",(d,w)->{try{pref.edit().putInt("maxClients",Math.max(1,Integer.parseInt(e.getText().toString()))).apply();show(SETTINGS);}catch(Exception x){toast("Invalid number");}}).setNegativeButton("Cancel",null).show();}
    void ipList(boolean block){String key=block?"blockIps":"allowIps";EditText e=input(pref.getString(key,""));e.setHint("192.168.1.10, 192.168.1.11");new AlertDialog.Builder(this).setTitle(block?"IP Blocklist":"IP Allowlist").setMessage("Comma-separated IPv4/IPv6 addresses").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{pref.edit().putString(key,e.getText().toString().trim()).apply();toast("IP list saved");}).show();}
    void security(){show(SETTINGS);}

    void network(){body.addView(label("NETWORK / INTERFACE"));rowTile(R.drawable.ic_wifi,"Wi‑Fi / LAN IP",WebServerService.wifiIp(this),()->copyText(WebServerService.wifiIp(this)));rowTile(R.drawable.ic_network,"Mobile Data IP",WebServerService.cellularIp(this),()->copyText(WebServerService.cellularIp(this)));rowTile(R.drawable.ic_globe,"Active Server URL",WebServerService.currentUrl(this),()->copyUrl());rowTile(R.drawable.ic_network,"Interface",WebServerService.interfaceName(this),()->toast(WebServerService.networkInfo(this)));rowTile(R.drawable.ic_dashboard,"Gateway / DNS","Detected from active network",()->toast(WebServerService.networkInfo(this)));LinearLayout c=card();c.addView(text("Server binding",15,WHITE));c.addView(text("0.0.0.0  •  all available interfaces",11,MUTED));c.addView(text("Wi‑Fi usually provides a LAN URL. Mobile-data IP visibility depends on carrier NAT/firewall; the app will still bind to the cellular interface when available.",10,MUTED));body.addView(c);}
    void logs(){LinearLayout top=new LinearLayout(this);Button clear=button("Clear Log"),refresh=button("Refresh");top.addView(clear,new LinearLayout.LayoutParams(0,dp(44),1));top.addView(refresh,new LinearLayout.LayoutParams(0,dp(44),1));clear.setOnClickListener(v->{WebServerService.clearLogs();show(LOGS);toast("Logs cleared");});refresh.setOnClickListener(v->show(LOGS));body.addView(top);TextView l=text(WebServerService.logsText(),10,WHITE);l.setTypeface(Typeface.MONOSPACE);l.setPadding(dp(12),dp(12),dp(12),dp(12));l.setBackground(bg(PANEL,SURFACE,16));body.addView(l,new LinearLayout.LayoutParams(-1,-2));}
    void aboutPage(){LinearLayout c=card();ImageView i=icon(R.drawable.ic_server,70);i.setColorFilter(CYAN);c.setGravity(Gravity.CENTER_HORIZONTAL);c.addView(i);TextView n=text("Salam Web Server",22,WHITE);n.setTypeface(null,1);c.addView(n);c.addView(text("Version 10.0 • Android Local Web Server",11,MUTED));body.addView(c);body.addView(label("DEVELOPER"));rowTile(R.drawable.ic_info,"Abdus Salam","Developer • 09696590864",()->toast("Email: salam230864@gmail.com"));rowTile(R.drawable.ic_email,"Email","salam230864@gmail.com",()->email());rowTile(R.drawable.ic_message,"Messenger","m.me/Salam.864",()->messenger());body.addView(label("MODULES"));String[] fs={"Live server dashboard","Wi‑Fi + mobile data interface detection","CPU / RAM / storage monitor","Live clients + request logs","Password + IP allow/block controls","Rate limiting + client limit","Advanced file manager + editor","Upload + ZIP extract","QR server sharing","Browser control panel","Themes + animations + premium UI","Background server notification"};for(String x:fs)body.addView(feature(x));}
    View feature(String s){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView c=text("✓",20,GREEN);r.addView(c,new LinearLayout.LayoutParams(dp(36),dp(42)));r.addView(text(s,12,WHITE),new LinearLayout.LayoutParams(0,dp(42),1));return r;}
    void browserPage(){body.addView(label("BROWSER PREVIEW"));LinearLayout c=card();TextView t=text("SALAM WEB SERVER",11,CYAN);t.setGravity(Gravity.CENTER);c.addView(t);TextView n=text("Local Server Control Panel",24,WHITE);n.setTypeface(null,1);n.setGravity(Gravity.CENTER);c.addView(n,new LinearLayout.LayoutParams(-1,dp(45)));TextView st=text(WebServerService.running?"● ONLINE":"● OFFLINE",11,WebServerService.running?GREEN:RED);st.setGravity(Gravity.CENTER);c.addView(st);body.addView(c);rowTile(R.drawable.ic_folder,"View Files","Open the hosted web root",()->openBrowser());rowTile(R.drawable.ic_dashboard,"Server Info","IP • port • requests • clients",()->show(NETWORK));rowTile(R.drawable.ic_log,"Live Logs","Request history",()->show(LOGS));rowTile(R.drawable.ic_settings,"Server Settings","Manage server configuration",()->show(SETTINGS));}

    void qr(){if(!WebServerService.running){toast("Start the server first");return;}try{String u=WebServerService.currentUrl(this);BitMatrix m=new QRCodeWriter().encode(u,BarcodeFormat.QR_CODE,720,720);Bitmap b=Bitmap.createBitmap(720,720,Bitmap.Config.RGB_565);for(int x=0;x<720;x++)for(int y=0;y<720;y++)b.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);ImageView iv=new ImageView(this);iv.setImageBitmap(b);iv.setPadding(dp(16),dp(16),dp(16),dp(16));new AlertDialog.Builder(this).setTitle("QR Server Sharing").setMessage(u).setView(iv).setPositiveButton("Share URL",(d,w)->share(u)).setNegativeButton("Close",null).show();}catch(Exception e){toast(e.getMessage());}}
    void themeDialog(){String[] x={"Electric Blue","Cyan Night","Purple Neon","Emerald","Amber","Ocean"};new AlertDialog.Builder(this).setTitle("Choose Theme").setSingleChoiceItems(x,pref.getInt("theme",0),(d,w)->{pref.edit().putInt("theme",w).apply();d.dismiss();appShell();toast("Theme changed");}).show();}

    void server(boolean start){try{Intent i=new Intent(this,WebServerService.class);i.setAction(start?"START":"STOP");if(start&&Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception e){toast(e.getMessage());}}
    void copyUrl(){copyText(WebServerService.currentUrl(this));}void copyText(String s){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Salam Web Server",s));toast("Copied to clipboard");}
    void openBrowser(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(WebServerService.currentUrl(this))));}catch(Exception e){toast("No browser found");}}
    void share(String s){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,s);startActivity(Intent.createChooser(i,"Share Server URL"));}void messenger(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://m.me/Salam.864")));}catch(Exception e){toast("Messenger unavailable");}}void email(){try{startActivity(new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:salam230864@gmail.com")));}catch(Exception e){toast("Email app unavailable");}}
    void menuDialog(){String[] x={"Home","Web Files","Network Info","Server Logs","Server Settings","About","Browser Control Panel"};int[] y={HOME,FILES,NETWORK,LOGS,SETTINGS,ABOUT,BROWSER};new AlertDialog.Builder(this).setTitle("Salam Web Server").setItems(x,(d,w)->show(y[w])).show();}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    String storageText(){StatFs s=new StatFs(getFilesDir().getAbsolutePath());long total=s.getTotalBytes(),free=s.getAvailableBytes();return format(total-free)+" / "+format(total);}
    String cpuUsage(){try{BufferedReader r=new BufferedReader(new FileReader("/proc/stat"));String line=r.readLine();r.close();if(line==null||!line.startsWith("cpu "))return "—";String[] a=line.trim().split("\\s+");long user=Long.parseLong(a[1]),nice=Long.parseLong(a[2]),sys=Long.parseLong(a[3]),idle=Long.parseLong(a[4]);long total=user+nice+sys+idle;long busy=total-idle;Long ot=pref.getLong("cpuTotal",-1),ob=pref.getLong("cpuBusy",-1);pref.edit().putLong("cpuTotal",total).putLong("cpuBusy",busy).apply();if(ot>0&&total>ot)return String.format(Locale.US,"%.0f%%",100.0*(busy-ob)/(double)(total-ot));return "0%";}catch(Exception e){return "—";}}

    class StatusLights extends View{Paint p=new Paint(1);ValueAnimator pulse;StatusLights(Context c){super(c);pulse=ValueAnimator.ofFloat(.65f,1f,.65f);pulse.setDuration(1100);pulse.setRepeatCount(ValueAnimator.INFINITE);pulse.addUpdateListener(v->invalidate());pulse.start();}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();for(int i=0;i<7;i++){float x=dp(9+i*17),y=h/2f;int col=WebServerService.running?STATUS_COLORS[i]:RED;float r=dp(5);p.setColor(col);p.setShadowLayer(WebServerService.running?dp(8)*((Float)pulse.getAnimatedValue()):0,0,0,col);setLayerType(View.LAYER_TYPE_SOFTWARE,p);c.drawCircle(x,y,r,p);if(WebServerService.running&&i<6){p.setColor(Color.argb(90,255,255,255));c.drawCircle(x-dp(1),y-dp(1),dp(1.5f),p);}}}}
    static class Wave extends View{Paint p=new Paint(1);Path path=new Path();Wave(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();int theme=getContext().getSharedPreferences("server",Context.MODE_PRIVATE).getInt("theme",0);int a=BG,b=SURFACE,line=BLUE;if(theme==1){b=Color.rgb(4,50,70);line=CYAN;}else if(theme==2){a=Color.rgb(12,5,28);b=Color.rgb(50,12,85);line=Color.rgb(190,80,255);}else if(theme==3){a=Color.rgb(2,21,18);b=Color.rgb(5,62,48);line=GREEN;}else if(theme==4){a=Color.rgb(30,10,4);b=Color.rgb(75,28,8);line=Color.rgb(255,145,30);}else if(theme==5){a=Color.rgb(3,8,28);b=Color.rgb(13,39,82);line=Color.rgb(72,135,255);}p.setShader(new LinearGradient(0,0,w,h,a,b,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.3f));p.setColor(line);for(int j=0;j<4;j++){path.reset();for(int x=0;x<=w;x+=10){float y=h*.73f+j*dp(16)+(float)Math.sin(x*.013+j)*dp(18);if(x==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p);}p.setStyle(Paint.Style.FILL);}}
}
